package com.iconfluence.sms.model;

public class IcSmsCustomerContact extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.GID
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.CID
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.SEX
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.DEPARTMENT
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.POSITION
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.QUHAO
     *
     * @mbg.generated
     */
    private String quhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.EXTENSION
     *
     * @mbg.generated
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.MOBILE
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.QQ
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.MSN
     *
     * @mbg.generated
     */
    private String msn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.ICQ
     *
     * @mbg.generated
     */
    private String icq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.IS_IMPORTANT
     *
     * @mbg.generated
     */
    private String isImportant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.CREATE_TIME
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.FAX
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.AREA_CODE
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.AREA
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.MAIN_CONTACT
     *
     * @mbg.generated
     */
    private Integer mainContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.GRADE
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_customer_contact.LAST_TIME
     *
     * @mbg.generated
     */
    private String lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    public IcSmsCustomerContact(String gid, String cid, String name, Integer sex, String department, String position, String quhao, String phone, String extension, String mobile, String qq, String msn, String icq, String email, String isImportant, String remark, String createTime, String fax, String areaCode, String area, Integer mainContact, String grade, String lastTime) {
        this.gid = gid;
        this.cid = cid;
        this.name = name;
        this.sex = sex;
        this.department = department;
        this.position = position;
        this.quhao = quhao;
        this.phone = phone;
        this.extension = extension;
        this.mobile = mobile;
        this.qq = qq;
        this.msn = msn;
        this.icq = icq;
        this.email = email;
        this.isImportant = isImportant;
        this.remark = remark;
        this.createTime = createTime;
        this.fax = fax;
        this.areaCode = areaCode;
        this.area = area;
        this.mainContact = mainContact;
        this.grade = grade;
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    public IcSmsCustomerContact() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.GID
     *
     * @return the value of ic_sms_customer_contact.GID
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.GID
     *
     * @param gid the value for ic_sms_customer_contact.GID
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.CID
     *
     * @return the value of ic_sms_customer_contact.CID
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.CID
     *
     * @param cid the value for ic_sms_customer_contact.CID
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.NAME
     *
     * @return the value of ic_sms_customer_contact.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.NAME
     *
     * @param name the value for ic_sms_customer_contact.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.SEX
     *
     * @return the value of ic_sms_customer_contact.SEX
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.SEX
     *
     * @param sex the value for ic_sms_customer_contact.SEX
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.DEPARTMENT
     *
     * @return the value of ic_sms_customer_contact.DEPARTMENT
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.DEPARTMENT
     *
     * @param department the value for ic_sms_customer_contact.DEPARTMENT
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.POSITION
     *
     * @return the value of ic_sms_customer_contact.POSITION
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.POSITION
     *
     * @param position the value for ic_sms_customer_contact.POSITION
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.QUHAO
     *
     * @return the value of ic_sms_customer_contact.QUHAO
     *
     * @mbg.generated
     */
    public String getQuhao() {
        return quhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.QUHAO
     *
     * @param quhao the value for ic_sms_customer_contact.QUHAO
     *
     * @mbg.generated
     */
    public void setQuhao(String quhao) {
        this.quhao = quhao == null ? null : quhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.PHONE
     *
     * @return the value of ic_sms_customer_contact.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.PHONE
     *
     * @param phone the value for ic_sms_customer_contact.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.EXTENSION
     *
     * @return the value of ic_sms_customer_contact.EXTENSION
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.EXTENSION
     *
     * @param extension the value for ic_sms_customer_contact.EXTENSION
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.MOBILE
     *
     * @return the value of ic_sms_customer_contact.MOBILE
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.MOBILE
     *
     * @param mobile the value for ic_sms_customer_contact.MOBILE
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.QQ
     *
     * @return the value of ic_sms_customer_contact.QQ
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.QQ
     *
     * @param qq the value for ic_sms_customer_contact.QQ
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.MSN
     *
     * @return the value of ic_sms_customer_contact.MSN
     *
     * @mbg.generated
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.MSN
     *
     * @param msn the value for ic_sms_customer_contact.MSN
     *
     * @mbg.generated
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.ICQ
     *
     * @return the value of ic_sms_customer_contact.ICQ
     *
     * @mbg.generated
     */
    public String getIcq() {
        return icq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.ICQ
     *
     * @param icq the value for ic_sms_customer_contact.ICQ
     *
     * @mbg.generated
     */
    public void setIcq(String icq) {
        this.icq = icq == null ? null : icq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.EMAIL
     *
     * @return the value of ic_sms_customer_contact.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.EMAIL
     *
     * @param email the value for ic_sms_customer_contact.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.IS_IMPORTANT
     *
     * @return the value of ic_sms_customer_contact.IS_IMPORTANT
     *
     * @mbg.generated
     */
    public String getIsImportant() {
        return isImportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.IS_IMPORTANT
     *
     * @param isImportant the value for ic_sms_customer_contact.IS_IMPORTANT
     *
     * @mbg.generated
     */
    public void setIsImportant(String isImportant) {
        this.isImportant = isImportant == null ? null : isImportant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.REMARK
     *
     * @return the value of ic_sms_customer_contact.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.REMARK
     *
     * @param remark the value for ic_sms_customer_contact.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.CREATE_TIME
     *
     * @return the value of ic_sms_customer_contact.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.CREATE_TIME
     *
     * @param createTime the value for ic_sms_customer_contact.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.FAX
     *
     * @return the value of ic_sms_customer_contact.FAX
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.FAX
     *
     * @param fax the value for ic_sms_customer_contact.FAX
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.AREA_CODE
     *
     * @return the value of ic_sms_customer_contact.AREA_CODE
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.AREA_CODE
     *
     * @param areaCode the value for ic_sms_customer_contact.AREA_CODE
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.AREA
     *
     * @return the value of ic_sms_customer_contact.AREA
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.AREA
     *
     * @param area the value for ic_sms_customer_contact.AREA
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.MAIN_CONTACT
     *
     * @return the value of ic_sms_customer_contact.MAIN_CONTACT
     *
     * @mbg.generated
     */
    public Integer getMainContact() {
        return mainContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.MAIN_CONTACT
     *
     * @param mainContact the value for ic_sms_customer_contact.MAIN_CONTACT
     *
     * @mbg.generated
     */
    public void setMainContact(Integer mainContact) {
        this.mainContact = mainContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.GRADE
     *
     * @return the value of ic_sms_customer_contact.GRADE
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.GRADE
     *
     * @param grade the value for ic_sms_customer_contact.GRADE
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_customer_contact.LAST_TIME
     *
     * @return the value of ic_sms_customer_contact.LAST_TIME
     *
     * @mbg.generated
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_customer_contact.LAST_TIME
     *
     * @param lastTime the value for ic_sms_customer_contact.LAST_TIME
     *
     * @mbg.generated
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime == null ? null : lastTime.trim();
    }
}