package com.iconfluence.sms.model;

public class IcSmsContract extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.GID
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.CUSTOMER_NAME
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.TRADE
     *
     * @mbg.generated
     */
    private String trade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.TERM
     *
     * @mbg.generated
     */
    private String term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.CONTRACT_TIME
     *
     * @mbg.generated
     */
    private String contractTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.OVER_TIME
     *
     * @mbg.generated
     */
    private String overTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.COOPERATION_TYPE
     *
     * @mbg.generated
     */
    private String cooperationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.RETURN_TIME
     *
     * @mbg.generated
     */
    private String returnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.QUALITY
     *
     * @mbg.generated
     */
    private String quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.UID
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.PROJ_CODE
     *
     * @mbg.generated
     */
    private String projCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_contract.EN_NAME
     *
     * @mbg.generated
     */
    private String enName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    public IcSmsContract(String gid, String customerName, String name, String type, String trade, String term, String contractTime, String overTime, String status, String cooperationType, String returnTime, String quality, String remark, String uid, String projCode, String enName) {
        this.gid = gid;
        this.customerName = customerName;
        this.name = name;
        this.type = type;
        this.trade = trade;
        this.term = term;
        this.contractTime = contractTime;
        this.overTime = overTime;
        this.status = status;
        this.cooperationType = cooperationType;
        this.returnTime = returnTime;
        this.quality = quality;
        this.remark = remark;
        this.uid = uid;
        this.projCode = projCode;
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    public IcSmsContract() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.GID
     *
     * @return the value of ic_sms_contract.GID
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.GID
     *
     * @param gid the value for ic_sms_contract.GID
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.CUSTOMER_NAME
     *
     * @return the value of ic_sms_contract.CUSTOMER_NAME
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.CUSTOMER_NAME
     *
     * @param customerName the value for ic_sms_contract.CUSTOMER_NAME
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.NAME
     *
     * @return the value of ic_sms_contract.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.NAME
     *
     * @param name the value for ic_sms_contract.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.TYPE
     *
     * @return the value of ic_sms_contract.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.TYPE
     *
     * @param type the value for ic_sms_contract.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.TRADE
     *
     * @return the value of ic_sms_contract.TRADE
     *
     * @mbg.generated
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.TRADE
     *
     * @param trade the value for ic_sms_contract.TRADE
     *
     * @mbg.generated
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.TERM
     *
     * @return the value of ic_sms_contract.TERM
     *
     * @mbg.generated
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.TERM
     *
     * @param term the value for ic_sms_contract.TERM
     *
     * @mbg.generated
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.CONTRACT_TIME
     *
     * @return the value of ic_sms_contract.CONTRACT_TIME
     *
     * @mbg.generated
     */
    public String getContractTime() {
        return contractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.CONTRACT_TIME
     *
     * @param contractTime the value for ic_sms_contract.CONTRACT_TIME
     *
     * @mbg.generated
     */
    public void setContractTime(String contractTime) {
        this.contractTime = contractTime == null ? null : contractTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.OVER_TIME
     *
     * @return the value of ic_sms_contract.OVER_TIME
     *
     * @mbg.generated
     */
    public String getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.OVER_TIME
     *
     * @param overTime the value for ic_sms_contract.OVER_TIME
     *
     * @mbg.generated
     */
    public void setOverTime(String overTime) {
        this.overTime = overTime == null ? null : overTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.STATUS
     *
     * @return the value of ic_sms_contract.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.STATUS
     *
     * @param status the value for ic_sms_contract.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.COOPERATION_TYPE
     *
     * @return the value of ic_sms_contract.COOPERATION_TYPE
     *
     * @mbg.generated
     */
    public String getCooperationType() {
        return cooperationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.COOPERATION_TYPE
     *
     * @param cooperationType the value for ic_sms_contract.COOPERATION_TYPE
     *
     * @mbg.generated
     */
    public void setCooperationType(String cooperationType) {
        this.cooperationType = cooperationType == null ? null : cooperationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.RETURN_TIME
     *
     * @return the value of ic_sms_contract.RETURN_TIME
     *
     * @mbg.generated
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.RETURN_TIME
     *
     * @param returnTime the value for ic_sms_contract.RETURN_TIME
     *
     * @mbg.generated
     */
    public void setReturnTime(String returnTime) {
        this.returnTime = returnTime == null ? null : returnTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.QUALITY
     *
     * @return the value of ic_sms_contract.QUALITY
     *
     * @mbg.generated
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.QUALITY
     *
     * @param quality the value for ic_sms_contract.QUALITY
     *
     * @mbg.generated
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.REMARK
     *
     * @return the value of ic_sms_contract.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.REMARK
     *
     * @param remark the value for ic_sms_contract.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.UID
     *
     * @return the value of ic_sms_contract.UID
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.UID
     *
     * @param uid the value for ic_sms_contract.UID
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.PROJ_CODE
     *
     * @return the value of ic_sms_contract.PROJ_CODE
     *
     * @mbg.generated
     */
    public String getProjCode() {
        return projCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.PROJ_CODE
     *
     * @param projCode the value for ic_sms_contract.PROJ_CODE
     *
     * @mbg.generated
     */
    public void setProjCode(String projCode) {
        this.projCode = projCode == null ? null : projCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_contract.EN_NAME
     *
     * @return the value of ic_sms_contract.EN_NAME
     *
     * @mbg.generated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_contract.EN_NAME
     *
     * @param enName the value for ic_sms_contract.EN_NAME
     *
     * @mbg.generated
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }
}