package com.iconfluence.sms.model;

public class IcSmsAuthority extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.gid
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.machine
     *
     * @mbg.generated
     */
    private String machine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.roles
     *
     * @mbg.generated
     */
    private String roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_authority.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_authority
     *
     * @mbg.generated
     */
    public IcSmsAuthority(String gid, String name, String keyword, String machine, String roles, String state) {
        this.gid = gid;
        this.name = name;
        this.keyword = keyword;
        this.machine = machine;
        this.roles = roles;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_authority
     *
     * @mbg.generated
     */
    public IcSmsAuthority() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.gid
     *
     * @return the value of ic_sms_authority.gid
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.gid
     *
     * @param gid the value for ic_sms_authority.gid
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.name
     *
     * @return the value of ic_sms_authority.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.name
     *
     * @param name the value for ic_sms_authority.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.keyword
     *
     * @return the value of ic_sms_authority.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.keyword
     *
     * @param keyword the value for ic_sms_authority.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.machine
     *
     * @return the value of ic_sms_authority.machine
     *
     * @mbg.generated
     */
    public String getMachine() {
        return machine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.machine
     *
     * @param machine the value for ic_sms_authority.machine
     *
     * @mbg.generated
     */
    public void setMachine(String machine) {
        this.machine = machine == null ? null : machine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.roles
     *
     * @return the value of ic_sms_authority.roles
     *
     * @mbg.generated
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.roles
     *
     * @param roles the value for ic_sms_authority.roles
     *
     * @mbg.generated
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_authority.state
     *
     * @return the value of ic_sms_authority.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_authority.state
     *
     * @param state the value for ic_sms_authority.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}