package com.iconfluence.sms.model;

public class IcSmsAccessControl extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.gid
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.authid
     *
     * @mbg.generated
     */
    private String authid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.authname
     *
     * @mbg.generated
     */
    private String authname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_access_control.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    public IcSmsAccessControl(String gid, String authid, String authname, String userid, String username, String state) {
        this.gid = gid;
        this.authid = authid;
        this.authname = authname;
        this.userid = userid;
        this.username = username;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    public IcSmsAccessControl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.gid
     *
     * @return the value of ic_sms_access_control.gid
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.gid
     *
     * @param gid the value for ic_sms_access_control.gid
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.authid
     *
     * @return the value of ic_sms_access_control.authid
     *
     * @mbg.generated
     */
    public String getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.authid
     *
     * @param authid the value for ic_sms_access_control.authid
     *
     * @mbg.generated
     */
    public void setAuthid(String authid) {
        this.authid = authid == null ? null : authid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.authname
     *
     * @return the value of ic_sms_access_control.authname
     *
     * @mbg.generated
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.authname
     *
     * @param authname the value for ic_sms_access_control.authname
     *
     * @mbg.generated
     */
    public void setAuthname(String authname) {
        this.authname = authname == null ? null : authname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.userid
     *
     * @return the value of ic_sms_access_control.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.userid
     *
     * @param userid the value for ic_sms_access_control.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.username
     *
     * @return the value of ic_sms_access_control.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.username
     *
     * @param username the value for ic_sms_access_control.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_access_control.state
     *
     * @return the value of ic_sms_access_control.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_access_control.state
     *
     * @param state the value for ic_sms_access_control.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}