package com.iconfluence.sms.model;

public class IcSmsAddress extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.areaId
     *
     * @mbg.generated
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.areaCode
     *
     * @mbg.generated
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.areaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.cityCode
     *
     * @mbg.generated
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.center
     *
     * @mbg.generated
     */
    private String center;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_address.parentId
     *
     * @mbg.generated
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public IcSmsAddress(Integer areaid, String areacode, String areaname, Byte level, String citycode, String center, Integer parentid) {
        this.areaid = areaid;
        this.areacode = areacode;
        this.areaname = areaname;
        this.level = level;
        this.citycode = citycode;
        this.center = center;
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public IcSmsAddress() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.areaId
     *
     * @return the value of ic_sms_address.areaId
     *
     * @mbg.generated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.areaId
     *
     * @param areaid the value for ic_sms_address.areaId
     *
     * @mbg.generated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.areaCode
     *
     * @return the value of ic_sms_address.areaCode
     *
     * @mbg.generated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.areaCode
     *
     * @param areacode the value for ic_sms_address.areaCode
     *
     * @mbg.generated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode == null ? null : areacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.areaName
     *
     * @return the value of ic_sms_address.areaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.areaName
     *
     * @param areaname the value for ic_sms_address.areaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.level
     *
     * @return the value of ic_sms_address.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.level
     *
     * @param level the value for ic_sms_address.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.cityCode
     *
     * @return the value of ic_sms_address.cityCode
     *
     * @mbg.generated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.cityCode
     *
     * @param citycode the value for ic_sms_address.cityCode
     *
     * @mbg.generated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.center
     *
     * @return the value of ic_sms_address.center
     *
     * @mbg.generated
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.center
     *
     * @param center the value for ic_sms_address.center
     *
     * @mbg.generated
     */
    public void setCenter(String center) {
        this.center = center == null ? null : center.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_address.parentId
     *
     * @return the value of ic_sms_address.parentId
     *
     * @mbg.generated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_address.parentId
     *
     * @param parentid the value for ic_sms_address.parentId
     *
     * @mbg.generated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}