package com.iconfluence.sms.model;

public class IcSmsBid extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.gid
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.year
     *
     * @mbg.generated
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.bid_time
     *
     * @mbg.generated
     */
    private String bidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.trade
     *
     * @mbg.generated
     */
    private String trade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.project
     *
     * @mbg.generated
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.attend_company
     *
     * @mbg.generated
     */
    private String attendCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.hl_name
     *
     * @mbg.generated
     */
    private String hlName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_sms_bid.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public IcSmsBid(String gid, String year, String bidTime, String name, String trade, String project, String attendCompany, String hlName, String result, String remark) {
        this.gid = gid;
        this.year = year;
        this.bidTime = bidTime;
        this.name = name;
        this.trade = trade;
        this.project = project;
        this.attendCompany = attendCompany;
        this.hlName = hlName;
        this.result = result;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public IcSmsBid() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.gid
     *
     * @return the value of ic_sms_bid.gid
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.gid
     *
     * @param gid the value for ic_sms_bid.gid
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.year
     *
     * @return the value of ic_sms_bid.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.year
     *
     * @param year the value for ic_sms_bid.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.bid_time
     *
     * @return the value of ic_sms_bid.bid_time
     *
     * @mbg.generated
     */
    public String getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.bid_time
     *
     * @param bidTime the value for ic_sms_bid.bid_time
     *
     * @mbg.generated
     */
    public void setBidTime(String bidTime) {
        this.bidTime = bidTime == null ? null : bidTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.name
     *
     * @return the value of ic_sms_bid.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.name
     *
     * @param name the value for ic_sms_bid.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.trade
     *
     * @return the value of ic_sms_bid.trade
     *
     * @mbg.generated
     */
    public String getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.trade
     *
     * @param trade the value for ic_sms_bid.trade
     *
     * @mbg.generated
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.project
     *
     * @return the value of ic_sms_bid.project
     *
     * @mbg.generated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.project
     *
     * @param project the value for ic_sms_bid.project
     *
     * @mbg.generated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.attend_company
     *
     * @return the value of ic_sms_bid.attend_company
     *
     * @mbg.generated
     */
    public String getAttendCompany() {
        return attendCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.attend_company
     *
     * @param attendCompany the value for ic_sms_bid.attend_company
     *
     * @mbg.generated
     */
    public void setAttendCompany(String attendCompany) {
        this.attendCompany = attendCompany == null ? null : attendCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.hl_name
     *
     * @return the value of ic_sms_bid.hl_name
     *
     * @mbg.generated
     */
    public String getHlName() {
        return hlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.hl_name
     *
     * @param hlName the value for ic_sms_bid.hl_name
     *
     * @mbg.generated
     */
    public void setHlName(String hlName) {
        this.hlName = hlName == null ? null : hlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.result
     *
     * @return the value of ic_sms_bid.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.result
     *
     * @param result the value for ic_sms_bid.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_sms_bid.remark
     *
     * @return the value of ic_sms_bid.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_sms_bid.remark
     *
     * @param remark the value for ic_sms_bid.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}