package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsPurchase;
import com.iconfluence.sms.model.IcSmsPurchaseExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsPurchaseMapper extends BaseMapper<IcSmsPurchase, IcSmsPurchaseExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPurchaseSqlProvider.class, method="countByExample")
    long countByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsPurchaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_purchase",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_purchase (gid, name, ",
        "usercode, password, ",
        "site, uid, create_time, ",
        "reg_time)",
        "values (#{gid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{usercode,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{site,jdbcType=VARCHAR}, #{uid,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{regTime,jdbcType=VARCHAR})"
    })
    int insert(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsPurchaseSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPurchaseSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="usercode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="site", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reg_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsPurchase> selectByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, name, usercode, password, site, uid, create_time, reg_time",
        "from ic_sms_purchase",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="usercode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="site", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reg_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsPurchase selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsPurchase record, @Param("example") IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsPurchase record, @Param("example") IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_purchase",
        "set name = #{name,jdbcType=VARCHAR},",
          "usercode = #{usercode,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "site = #{site,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "reg_time = #{regTime,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsPurchase record);
}