package com.iconfluence.sms.mapper;

import com.iconfluence.sms.mapper.customMapper.IIcSmsPwdMapper;
import com.iconfluence.sms.model.IcSmsPwd;
import com.iconfluence.sms.model.IcSmsPwdExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsPwdMapper extends BaseMapper<IcSmsPwd, IcSmsPwdExample>, IIcSmsPwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPwdSqlProvider.class, method="countByExample")
    long countByExample(IcSmsPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsPwdSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_pwd",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_pwd (gid, pwd, ",
        "rid, type)",
        "values (#{gid,jdbcType=VARCHAR}, #{pwd,jdbcType=VARCHAR}, ",
        "#{rid,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR})"
    })
    int insert(IcSmsPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsPwdSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPwdSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="pwd", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="rid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsPwd> selectByExample(IcSmsPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, pwd, rid, type",
        "from ic_sms_pwd",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="pwd", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="rid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsPwd selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPwdSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsPwd record, @Param("example") IcSmsPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPwdSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsPwd record, @Param("example") IcSmsPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPwdSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_pwd
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_pwd",
        "set pwd = #{pwd,jdbcType=VARCHAR},",
          "rid = #{rid,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsPwd record);
}