package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsEnum;
import com.iconfluence.sms.model.IcSmsEnumExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsEnumMapper extends BaseMapper<IcSmsEnum, IcSmsEnumExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsEnumSqlProvider.class, method="countByExample")
    long countByExample(IcSmsEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsEnumSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_enum",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_enum (gid, type, ",
        "type_name, code, ",
        "name)",
        "values (#{gid,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{typeName,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR})"
    })
    int insert(IcSmsEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsEnumSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsEnumSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsEnum> selectByExample(IcSmsEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, type, type_name, code, name",
        "from ic_sms_enum",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsEnum selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsEnumSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsEnum record, @Param("example") IcSmsEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsEnumSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsEnum record, @Param("example") IcSmsEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsEnumSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_enum
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_enum",
        "set type = #{type,jdbcType=VARCHAR},",
          "type_name = #{typeName,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsEnum record);
}