package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsCustomerContact;
import com.iconfluence.sms.model.IcSmsCustomerContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IcSmsCustomerContactMapper extends BaseMapper<IcSmsCustomerContact, IcSmsCustomerContactExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerContactSqlProvider.class, method="countByExample")
    long countByExample(IcSmsCustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsCustomerContactSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsCustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_customer_contact",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_customer_contact (GID, CID, ",
        "NAME, SEX, DEPARTMENT, ",
        "POSITION, QUHAO, ",
        "PHONE, EXTENSION, ",
        "MOBILE, QQ, MSN, ",
        "ICQ, EMAIL, IS_IMPORTANT, ",
        "REMARK, CREATE_TIME, ",
        "FAX, AREA_CODE, AREA, ",
        "MAIN_CONTACT, GRADE, ",
        "LAST_TIME)",
        "values (#{gid,jdbcType=VARCHAR}, #{cid,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{sex,jdbcType=INTEGER}, #{department,jdbcType=VARCHAR}, ",
        "#{position,jdbcType=VARCHAR}, #{quhao,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{extension,jdbcType=VARCHAR}, ",
        "#{mobile,jdbcType=VARCHAR}, #{qq,jdbcType=VARCHAR}, #{msn,jdbcType=VARCHAR}, ",
        "#{icq,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{isImportant,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{fax,jdbcType=VARCHAR}, #{areaCode,jdbcType=VARCHAR}, #{area,jdbcType=VARCHAR}, ",
        "#{mainContact,jdbcType=INTEGER}, #{grade,jdbcType=VARCHAR}, ",
        "#{lastTime,jdbcType=VARCHAR})"
    })
    int insert(IcSmsCustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsCustomerContactSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsCustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerContactSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SEX", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="DEPARTMENT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="POSITION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUHAO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXTENSION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MOBILE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QQ", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ICQ", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EMAIL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="IS_IMPORTANT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FAX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AREA_CODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AREA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MAIN_CONTACT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="GRADE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LAST_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsCustomerContact> selectByExample(IcSmsCustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "GID, CID, NAME, SEX, DEPARTMENT, POSITION, QUHAO, PHONE, EXTENSION, MOBILE, ",
        "QQ, MSN, ICQ, EMAIL, IS_IMPORTANT, REMARK, CREATE_TIME, FAX, AREA_CODE, AREA, ",
        "MAIN_CONTACT, GRADE, LAST_TIME",
        "from ic_sms_customer_contact",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SEX", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="DEPARTMENT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="POSITION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUHAO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXTENSION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MOBILE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QQ", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ICQ", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EMAIL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="IS_IMPORTANT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FAX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AREA_CODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AREA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MAIN_CONTACT", javaType=Integer.class, jdbcType=JdbcType.INTEGER),
        @Arg(column="GRADE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LAST_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsCustomerContact selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerContactSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsCustomerContact record, @Param("example") IcSmsCustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerContactSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsCustomerContact record, @Param("example") IcSmsCustomerContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerContactSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsCustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_contact
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_customer_contact",
        "set CID = #{cid,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "SEX = #{sex,jdbcType=INTEGER},",
          "DEPARTMENT = #{department,jdbcType=VARCHAR},",
          "POSITION = #{position,jdbcType=VARCHAR},",
          "QUHAO = #{quhao,jdbcType=VARCHAR},",
          "PHONE = #{phone,jdbcType=VARCHAR},",
          "EXTENSION = #{extension,jdbcType=VARCHAR},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "QQ = #{qq,jdbcType=VARCHAR},",
          "MSN = #{msn,jdbcType=VARCHAR},",
          "ICQ = #{icq,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "IS_IMPORTANT = #{isImportant,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=VARCHAR},",
          "FAX = #{fax,jdbcType=VARCHAR},",
          "AREA_CODE = #{areaCode,jdbcType=VARCHAR},",
          "AREA = #{area,jdbcType=VARCHAR},",
          "MAIN_CONTACT = #{mainContact,jdbcType=INTEGER},",
          "GRADE = #{grade,jdbcType=VARCHAR},",
          "LAST_TIME = #{lastTime,jdbcType=VARCHAR}",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsCustomerContact record);
}