package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsCustomer;
import com.iconfluence.sms.model.IcSmsCustomerExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsCustomerMapper extends BaseMapper<IcSmsCustomer, IcSmsCustomerExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerSqlProvider.class, method="countByExample")
    long countByExample(IcSmsCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsCustomerSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_customer",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_customer (gid, code, ",
        "postalcode, name, ",
        "create_time, area, ",
        "address, site, origin, ",
        "grade, stff_name, ",
        "uid, trade, status, ",
        "reg_date, remark, ",
        "country, province, ",
        "city, next_time, ",
        "last_time)",
        "values (#{gid,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{postalcode,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=VARCHAR}, #{area,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{site,jdbcType=VARCHAR}, #{origin,jdbcType=VARCHAR}, ",
        "#{grade,jdbcType=VARCHAR}, #{stffName,jdbcType=VARCHAR}, ",
        "#{uid,jdbcType=VARCHAR}, #{trade,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{regDate,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{country,jdbcType=VARCHAR}, #{province,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{nextTime,jdbcType=VARCHAR}, ",
        "#{lastTime,jdbcType=VARCHAR})"
    })
    int insert(IcSmsCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsCustomerSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="postalcode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="area", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="address", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="site", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="origin", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="stff_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="trade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reg_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="country", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="next_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="last_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsCustomer> selectByExample(IcSmsCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, code, postalcode, name, create_time, area, address, site, origin, grade, ",
        "stff_name, uid, trade, status, reg_date, remark, country, province, city, next_time, ",
        "last_time",
        "from ic_sms_customer",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="postalcode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="area", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="address", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="site", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="origin", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="stff_name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="trade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="reg_date", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="country", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="province", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="city", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="next_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="last_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsCustomer selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsCustomer record, @Param("example") IcSmsCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsCustomer record, @Param("example") IcSmsCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_customer",
        "set code = #{code,jdbcType=VARCHAR},",
          "postalcode = #{postalcode,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "site = #{site,jdbcType=VARCHAR},",
          "origin = #{origin,jdbcType=VARCHAR},",
          "grade = #{grade,jdbcType=VARCHAR},",
          "stff_name = #{stffName,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=VARCHAR},",
          "trade = #{trade,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "reg_date = #{regDate,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "next_time = #{nextTime,jdbcType=VARCHAR},",
          "last_time = #{lastTime,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsCustomer record);
}