package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsBid;
import com.iconfluence.sms.model.IcSmsBidExample;
import com.iconfluence.sms.model.IcSmsBidExample.Criteria;
import com.iconfluence.sms.model.IcSmsBidExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class IcSmsBidSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String countByExample(IcSmsBidExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("ic_sms_bid");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String deleteByExample(IcSmsBidExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("ic_sms_bid");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String insertSelective(IcSmsBid record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ic_sms_bid");
        
        if (record.getGid() != null) {
            sql.VALUES("gid", "#{gid,jdbcType=VARCHAR}");
        }
        
        if (record.getYear() != null) {
            sql.VALUES("year", "#{year,jdbcType=VARCHAR}");
        }
        
        if (record.getBidTime() != null) {
            sql.VALUES("bid_time", "#{bidTime,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTrade() != null) {
            sql.VALUES("trade", "#{trade,jdbcType=VARCHAR}");
        }
        
        if (record.getProject() != null) {
            sql.VALUES("project", "#{project,jdbcType=VARCHAR}");
        }
        
        if (record.getAttendCompany() != null) {
            sql.VALUES("attend_company", "#{attendCompany,jdbcType=VARCHAR}");
        }
        
        if (record.getHlName() != null) {
            sql.VALUES("hl_name", "#{hlName,jdbcType=VARCHAR}");
        }
        
        if (record.getResult() != null) {
            sql.VALUES("result", "#{result,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String selectByExample(IcSmsBidExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("gid");
        } else {
            sql.SELECT("gid");
        }
        sql.SELECT("year");
        sql.SELECT("bid_time");
        sql.SELECT("name");
        sql.SELECT("trade");
        sql.SELECT("project");
        sql.SELECT("attend_company");
        sql.SELECT("hl_name");
        sql.SELECT("result");
        sql.SELECT("remark");
        sql.FROM("ic_sms_bid");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        IcSmsBid record = (IcSmsBid) parameter.get("record");
        IcSmsBidExample example = (IcSmsBidExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_bid");
        
        if (record.getGid() != null) {
            sql.SET("gid = #{record.gid,jdbcType=VARCHAR}");
        }
        
        if (record.getYear() != null) {
            sql.SET("year = #{record.year,jdbcType=VARCHAR}");
        }
        
        if (record.getBidTime() != null) {
            sql.SET("bid_time = #{record.bidTime,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getTrade() != null) {
            sql.SET("trade = #{record.trade,jdbcType=VARCHAR}");
        }
        
        if (record.getProject() != null) {
            sql.SET("project = #{record.project,jdbcType=VARCHAR}");
        }
        
        if (record.getAttendCompany() != null) {
            sql.SET("attend_company = #{record.attendCompany,jdbcType=VARCHAR}");
        }
        
        if (record.getHlName() != null) {
            sql.SET("hl_name = #{record.hlName,jdbcType=VARCHAR}");
        }
        
        if (record.getResult() != null) {
            sql.SET("result = #{record.result,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_bid");
        
        sql.SET("gid = #{record.gid,jdbcType=VARCHAR}");
        sql.SET("year = #{record.year,jdbcType=VARCHAR}");
        sql.SET("bid_time = #{record.bidTime,jdbcType=VARCHAR}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("trade = #{record.trade,jdbcType=VARCHAR}");
        sql.SET("project = #{record.project,jdbcType=VARCHAR}");
        sql.SET("attend_company = #{record.attendCompany,jdbcType=VARCHAR}");
        sql.SET("hl_name = #{record.hlName,jdbcType=VARCHAR}");
        sql.SET("result = #{record.result,jdbcType=VARCHAR}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        
        IcSmsBidExample example = (IcSmsBidExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(IcSmsBid record) {
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_bid");
        
        if (record.getYear() != null) {
            sql.SET("year = #{year,jdbcType=VARCHAR}");
        }
        
        if (record.getBidTime() != null) {
            sql.SET("bid_time = #{bidTime,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTrade() != null) {
            sql.SET("trade = #{trade,jdbcType=VARCHAR}");
        }
        
        if (record.getProject() != null) {
            sql.SET("project = #{project,jdbcType=VARCHAR}");
        }
        
        if (record.getAttendCompany() != null) {
            sql.SET("attend_company = #{attendCompany,jdbcType=VARCHAR}");
        }
        
        if (record.getHlName() != null) {
            sql.SET("hl_name = #{hlName,jdbcType=VARCHAR}");
        }
        
        if (record.getResult() != null) {
            sql.SET("result = #{result,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("gid = #{gid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_bid
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, IcSmsBidExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}