package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsDict;
import com.iconfluence.sms.model.IcSmsDictExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsDictMapper extends BaseMapper<IcSmsDict, IcSmsDictExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsDictSqlProvider.class, method="countByExample")
    long countByExample(IcSmsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsDictSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_dict",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_dict (gid, type, ",
        "name, idx, value, ",
        "update_time, remark)",
        "values (#{gid,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{idx,jdbcType=VARCHAR}, #{value,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(IcSmsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsDictSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsDictSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="idx", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="value", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsDict> selectByExample(IcSmsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, type, name, idx, value, update_time, remark",
        "from ic_sms_dict",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="idx", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="value", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsDict selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsDictSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsDict record, @Param("example") IcSmsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsDictSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsDict record, @Param("example") IcSmsDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsDictSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_dict
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_dict",
        "set type = #{type,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "idx = #{idx,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsDict record);
}