package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsUser;
import com.iconfluence.sms.model.IcSmsUserExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsUserMapper extends BaseMapper<IcSmsUser, IcSmsUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsUserSqlProvider.class, method="countByExample")
    long countByExample(IcSmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_user",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_user (gid, code, ",
        "name, password, ",
        "rid, pid, status)",
        "values (#{gid,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{rid,jdbcType=VARCHAR}, #{pid,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR})"
    })
    int insert(IcSmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsUserSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsUserSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="rid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="pid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsUser> selectByExample(IcSmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, code, name, password, rid, pid, status",
        "from ic_sms_user",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="name", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="password", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="rid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="pid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsUser selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsUser record, @Param("example") IcSmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsUser record, @Param("example") IcSmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_user
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_user",
        "set code = #{code,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "rid = #{rid,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsUser record);
}