package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsPurchase;
import com.iconfluence.sms.model.IcSmsPurchaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IcSmsPurchaseMapper extends BaseMapper<IcSmsPurchase, IcSmsPurchaseExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPurchaseSqlProvider.class, method="countByExample")
    long countByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsPurchaseSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_purchase",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_purchase (GID, NAME, ",
        "USERCODE, PASSWORD, ",
        "SITE, UID, CREATE_TIME, ",
        "REG_TIME, REMARK)",
        "values (#{gid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{usercode,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{site,jdbcType=VARCHAR}, #{uid,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{regTime,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsPurchaseSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsPurchaseSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="USERCODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PASSWORD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SITE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REG_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsPurchase> selectByExample(IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "GID, NAME, USERCODE, PASSWORD, SITE, UID, CREATE_TIME, REG_TIME, REMARK",
        "from ic_sms_purchase",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="USERCODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PASSWORD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SITE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REG_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsPurchase selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsPurchase record, @Param("example") IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsPurchase record, @Param("example") IcSmsPurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsPurchaseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsPurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_purchase
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_purchase",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "USERCODE = #{usercode,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "SITE = #{site,jdbcType=VARCHAR},",
          "UID = #{uid,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=VARCHAR},",
          "REG_TIME = #{regTime,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR}",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsPurchase record);
}