package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsContract;
import com.iconfluence.sms.model.IcSmsContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IcSmsContractMapper extends BaseMapper<IcSmsContract, IcSmsContractExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsContractSqlProvider.class, method="countByExample")
    long countByExample(IcSmsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsContractSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_contract",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_contract (GID, CUSTOMER_NAME, ",
        "NAME, TYPE, TRADE, ",
        "TERM, CONTRACT_TIME, ",
        "OVER_TIME, STATUS, ",
        "COOPERATION_TYPE, RETURN_TIME, ",
        "QUALITY, REMARK, ",
        "UID, PROJ_CODE, EN_NAME)",
        "values (#{gid,jdbcType=VARCHAR}, #{customerName,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{trade,jdbcType=VARCHAR}, ",
        "#{term,jdbcType=VARCHAR}, #{contractTime,jdbcType=VARCHAR}, ",
        "#{overTime,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{cooperationType,jdbcType=VARCHAR}, #{returnTime,jdbcType=VARCHAR}, ",
        "#{quality,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{uid,jdbcType=VARCHAR}, #{projCode,jdbcType=VARCHAR}, #{enName,jdbcType=VARCHAR})"
    })
    int insert(IcSmsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsContractSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsContractSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CUSTOMER_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRADE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTRACT_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="OVER_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COOPERATION_TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="RETURN_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUALITY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PROJ_CODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsContract> selectByExample(IcSmsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "GID, CUSTOMER_NAME, NAME, TYPE, TRADE, TERM, CONTRACT_TIME, OVER_TIME, STATUS, ",
        "COOPERATION_TYPE, RETURN_TIME, QUALITY, REMARK, UID, PROJ_CODE, EN_NAME",
        "from ic_sms_contract",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CUSTOMER_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRADE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTRACT_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="OVER_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COOPERATION_TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="RETURN_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUALITY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PROJ_CODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsContract selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsContractSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsContract record, @Param("example") IcSmsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsContractSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsContract record, @Param("example") IcSmsContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsContractSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_contract
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_contract",
        "set CUSTOMER_NAME = #{customerName,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "TYPE = #{type,jdbcType=VARCHAR},",
          "TRADE = #{trade,jdbcType=VARCHAR},",
          "TERM = #{term,jdbcType=VARCHAR},",
          "CONTRACT_TIME = #{contractTime,jdbcType=VARCHAR},",
          "OVER_TIME = #{overTime,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=VARCHAR},",
          "COOPERATION_TYPE = #{cooperationType,jdbcType=VARCHAR},",
          "RETURN_TIME = #{returnTime,jdbcType=VARCHAR},",
          "QUALITY = #{quality,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "UID = #{uid,jdbcType=VARCHAR},",
          "PROJ_CODE = #{projCode,jdbcType=VARCHAR},",
          "EN_NAME = #{enName,jdbcType=VARCHAR}",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsContract record);
}