package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsComeVisit;
import com.iconfluence.sms.model.IcSmsComeVisitExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsComeVisitMapper extends BaseMapper<IcSmsComeVisit, IcSmsComeVisitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsComeVisitSqlProvider.class, method="countByExample")
    long countByExample(IcSmsComeVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsComeVisitSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsComeVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_come_visit",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_come_visit (gid, year, ",
        "visit_time, objective, ",
        "c_user, hl_user, result, ",
        "remark, uid, visit_unit)",
        "values (#{gid,jdbcType=VARCHAR}, #{year,jdbcType=VARCHAR}, ",
        "#{visitTime,jdbcType=VARCHAR}, #{objective,jdbcType=VARCHAR}, ",
        "#{cUser,jdbcType=VARCHAR}, #{hlUser,jdbcType=VARCHAR}, #{result,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{uid,jdbcType=VARCHAR}, #{visitUnit,jdbcType=VARCHAR})"
    })
    int insert(IcSmsComeVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsComeVisitSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsComeVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsComeVisitSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="year", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="visit_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="objective", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="c_user", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="hl_user", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="result", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="visit_unit", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsComeVisit> selectByExample(IcSmsComeVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, year, visit_time, objective, c_user, hl_user, result, remark, uid, visit_unit",
        "from ic_sms_come_visit",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="year", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="visit_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="objective", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="c_user", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="hl_user", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="result", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="visit_unit", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsComeVisit selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsComeVisitSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsComeVisit record, @Param("example") IcSmsComeVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsComeVisitSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsComeVisit record, @Param("example") IcSmsComeVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsComeVisitSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsComeVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_come_visit
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_come_visit",
        "set year = #{year,jdbcType=VARCHAR},",
          "visit_time = #{visitTime,jdbcType=VARCHAR},",
          "objective = #{objective,jdbcType=VARCHAR},",
          "c_user = #{cUser,jdbcType=VARCHAR},",
          "hl_user = #{hlUser,jdbcType=VARCHAR},",
          "result = #{result,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=VARCHAR},",
          "visit_unit = #{visitUnit,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsComeVisit record);
}