package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsWorkRemind;
import com.iconfluence.sms.model.IcSmsWorkRemindExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsWorkRemindMapper extends BaseMapper<IcSmsWorkRemind, IcSmsWorkRemindExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsWorkRemindSqlProvider.class, method="countByExample")
    long countByExample(IcSmsWorkRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsWorkRemindSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsWorkRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_work_remind",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_work_remind (gid, theme, ",
        "update_time, uid, ",
        "start_time, over_time, ",
        "remarks, status)",
        "values (#{gid,jdbcType=VARCHAR}, #{theme,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{uid,jdbcType=VARCHAR}, ",
        "#{startTime,jdbcType=VARCHAR}, #{overTime,jdbcType=VARCHAR}, ",
        "#{remarks,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR})"
    })
    int insert(IcSmsWorkRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsWorkRemindSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsWorkRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsWorkRemindSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="theme", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="start_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="over_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remarks", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsWorkRemind> selectByExample(IcSmsWorkRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, theme, update_time, uid, start_time, over_time, remarks, status",
        "from ic_sms_work_remind",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="theme", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="update_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="uid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="start_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="over_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remarks", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="status", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsWorkRemind selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsWorkRemindSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsWorkRemind record, @Param("example") IcSmsWorkRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsWorkRemindSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsWorkRemind record, @Param("example") IcSmsWorkRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsWorkRemindSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsWorkRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_work_remind
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_work_remind",
        "set theme = #{theme,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=VARCHAR},",
          "over_time = #{overTime,jdbcType=VARCHAR},",
          "remarks = #{remarks,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsWorkRemind record);
}