package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsAccessControl;
import com.iconfluence.sms.model.IcSmsAccessControlExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsAccessControlMapper extends BaseMapper<IcSmsAccessControl, IcSmsAccessControlExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsAccessControlSqlProvider.class, method="countByExample")
    long countByExample(IcSmsAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsAccessControlSqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_access_control",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_access_control (gid, authid, ",
        "authname, userid, ",
        "usercode, state)",
        "values (#{gid,jdbcType=VARCHAR}, #{authid,jdbcType=VARCHAR}, ",
        "#{authname,jdbcType=VARCHAR}, #{userid,jdbcType=VARCHAR}, ",
        "#{usercode,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR})"
    })
    int insert(IcSmsAccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsAccessControlSqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsAccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsAccessControlSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="authid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="authname", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="usercode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="state", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsAccessControl> selectByExample(IcSmsAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, authid, authname, userid, usercode, state",
        "from ic_sms_access_control",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="authid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="authname", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="userid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="usercode", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="state", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsAccessControl selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsAccessControlSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsAccessControl record, @Param("example") IcSmsAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsAccessControlSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsAccessControl record, @Param("example") IcSmsAccessControlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsAccessControlSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsAccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_access_control
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_access_control",
        "set authid = #{authid,jdbcType=VARCHAR},",
          "authname = #{authname,jdbcType=VARCHAR},",
          "userid = #{userid,jdbcType=VARCHAR},",
          "usercode = #{usercode,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsAccessControl record);
}