package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsCustomerActivity;
import com.iconfluence.sms.model.IcSmsCustomerActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IcSmsCustomerActivityMapper extends BaseMapper<IcSmsCustomerActivity, IcSmsCustomerActivityExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerActivitySqlProvider.class, method="countByExample")
    long countByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsCustomerActivitySqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_customer_activity",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_customer_activity (GID, CID, ",
        "SUBJECT, CONTACT, ",
        "TOUCH_TIME, RECORD, ",
        "TYPE, NEXT_TIME, ",
        "POTENTIAL, REMARK, ",
        "CREATE_TIME, grade)",
        "values (#{gid,jdbcType=VARCHAR}, #{cid,jdbcType=VARCHAR}, ",
        "#{subject,jdbcType=VARCHAR}, #{contact,jdbcType=VARCHAR}, ",
        "#{touchTime,jdbcType=VARCHAR}, #{record,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{nextTime,jdbcType=VARCHAR}, ",
        "#{potential,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=VARCHAR}, #{grade,jdbcType=VARCHAR})"
    })
    int insert(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsCustomerActivitySqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerActivitySqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUBJECT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTACT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCH_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="RECORD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NEXT_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="POTENTIAL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsCustomerActivity> selectByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "GID, CID, SUBJECT, CONTACT, TOUCH_TIME, RECORD, TYPE, NEXT_TIME, POTENTIAL, ",
        "REMARK, CREATE_TIME, grade",
        "from ic_sms_customer_activity",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="GID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUBJECT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTACT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCH_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="RECORD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NEXT_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="POTENTIAL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREATE_TIME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsCustomerActivity selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsCustomerActivity record, @Param("example") IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsCustomerActivity record, @Param("example") IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_customer_activity",
        "set CID = #{cid,jdbcType=VARCHAR},",
          "SUBJECT = #{subject,jdbcType=VARCHAR},",
          "CONTACT = #{contact,jdbcType=VARCHAR},",
          "TOUCH_TIME = #{touchTime,jdbcType=VARCHAR},",
          "RECORD = #{record,jdbcType=VARCHAR},",
          "TYPE = #{type,jdbcType=VARCHAR},",
          "NEXT_TIME = #{nextTime,jdbcType=VARCHAR},",
          "POTENTIAL = #{potential,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=VARCHAR},",
          "grade = #{grade,jdbcType=VARCHAR}",
        "where GID = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsCustomerActivity record);
}