package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsCustomerActivity;
import com.iconfluence.sms.model.IcSmsCustomerActivityExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface IcSmsCustomerActivityMapper extends BaseMapper<IcSmsCustomerActivity, IcSmsCustomerActivityExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerActivitySqlProvider.class, method="countByExample")
    long countByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @DeleteProvider(type=IcSmsCustomerActivitySqlProvider.class, method="deleteByExample")
    int deleteByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ic_sms_customer_activity",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ic_sms_customer_activity (gid, cid, ",
        "subject, contact, ",
        "touch_time, record, ",
        "type, next_time, ",
        "grade, potential, ",
        "remark, create_time)",
        "values (#{gid,jdbcType=VARCHAR}, #{cid,jdbcType=VARCHAR}, ",
        "#{subject,jdbcType=VARCHAR}, #{contact,jdbcType=VARCHAR}, ",
        "#{touchTime,jdbcType=VARCHAR}, #{record,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{nextTime,jdbcType=VARCHAR}, ",
        "#{grade,jdbcType=VARCHAR}, #{potential,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR})"
    })
    int insert(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @InsertProvider(type=IcSmsCustomerActivitySqlProvider.class, method="insertSelective")
    int insertSelective(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @SelectProvider(type=IcSmsCustomerActivitySqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="cid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="subject", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="contact", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="touch_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="record", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="next_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="potential", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<IcSmsCustomerActivity> selectByExample(IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "gid, cid, subject, contact, touch_time, record, type, next_time, grade, potential, ",
        "remark, create_time",
        "from ic_sms_customer_activity",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="gid", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="cid", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="subject", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="contact", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="touch_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="record", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="type", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="next_time", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="grade", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="potential", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="remark", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="create_time", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    IcSmsCustomerActivity selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") IcSmsCustomerActivity record, @Param("example") IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") IcSmsCustomerActivity record, @Param("example") IcSmsCustomerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @UpdateProvider(type=IcSmsCustomerActivitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(IcSmsCustomerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_customer_activity
     *
     * @mbg.generated
     */
    @Update({
        "update ic_sms_customer_activity",
        "set cid = #{cid,jdbcType=VARCHAR},",
          "subject = #{subject,jdbcType=VARCHAR},",
          "contact = #{contact,jdbcType=VARCHAR},",
          "touch_time = #{touchTime,jdbcType=VARCHAR},",
          "record = #{record,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "next_time = #{nextTime,jdbcType=VARCHAR},",
          "grade = #{grade,jdbcType=VARCHAR},",
          "potential = #{potential,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR}",
        "where gid = #{gid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(IcSmsCustomerActivity record);
}