package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.IcSmsAddress;
import com.iconfluence.sms.model.IcSmsAddressExample;
import com.iconfluence.sms.model.IcSmsAddressExample.Criteria;
import com.iconfluence.sms.model.IcSmsAddressExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class IcSmsAddressSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String countByExample(IcSmsAddressExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("ic_sms_address");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String deleteByExample(IcSmsAddressExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("ic_sms_address");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String insertSelective(IcSmsAddress record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ic_sms_address");
        
        if (record.getAreaid() != null) {
            sql.VALUES("areaId", "#{areaid,jdbcType=INTEGER}");
        }
        
        if (record.getAreacode() != null) {
            sql.VALUES("areaCode", "#{areacode,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaname() != null) {
            sql.VALUES("areaName", "#{areaname,jdbcType=VARCHAR}");
        }
        
        if (record.getLevel() != null) {
            sql.VALUES("level", "#{level,jdbcType=TINYINT}");
        }
        
        if (record.getCitycode() != null) {
            sql.VALUES("cityCode", "#{citycode,jdbcType=VARCHAR}");
        }
        
        if (record.getCenter() != null) {
            sql.VALUES("center", "#{center,jdbcType=VARCHAR}");
        }
        
        if (record.getParentid() != null) {
            sql.VALUES("parentId", "#{parentid,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String selectByExample(IcSmsAddressExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("areaId");
        } else {
            sql.SELECT("areaId");
        }
        sql.SELECT("areaCode");
        sql.SELECT("areaName");
        sql.SELECT("level");
        sql.SELECT("cityCode");
        sql.SELECT("center");
        sql.SELECT("parentId");
        sql.FROM("ic_sms_address");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        IcSmsAddress record = (IcSmsAddress) parameter.get("record");
        IcSmsAddressExample example = (IcSmsAddressExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_address");
        
        if (record.getAreaid() != null) {
            sql.SET("areaId = #{record.areaid,jdbcType=INTEGER}");
        }
        
        if (record.getAreacode() != null) {
            sql.SET("areaCode = #{record.areacode,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaname() != null) {
            sql.SET("areaName = #{record.areaname,jdbcType=VARCHAR}");
        }
        
        if (record.getLevel() != null) {
            sql.SET("level = #{record.level,jdbcType=TINYINT}");
        }
        
        if (record.getCitycode() != null) {
            sql.SET("cityCode = #{record.citycode,jdbcType=VARCHAR}");
        }
        
        if (record.getCenter() != null) {
            sql.SET("center = #{record.center,jdbcType=VARCHAR}");
        }
        
        if (record.getParentid() != null) {
            sql.SET("parentId = #{record.parentid,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_address");
        
        sql.SET("areaId = #{record.areaid,jdbcType=INTEGER}");
        sql.SET("areaCode = #{record.areacode,jdbcType=VARCHAR}");
        sql.SET("areaName = #{record.areaname,jdbcType=VARCHAR}");
        sql.SET("level = #{record.level,jdbcType=TINYINT}");
        sql.SET("cityCode = #{record.citycode,jdbcType=VARCHAR}");
        sql.SET("center = #{record.center,jdbcType=VARCHAR}");
        sql.SET("parentId = #{record.parentid,jdbcType=INTEGER}");
        
        IcSmsAddressExample example = (IcSmsAddressExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(IcSmsAddress record) {
        SQL sql = new SQL();
        sql.UPDATE("ic_sms_address");
        
        if (record.getAreacode() != null) {
            sql.SET("areaCode = #{areacode,jdbcType=VARCHAR}");
        }
        
        if (record.getAreaname() != null) {
            sql.SET("areaName = #{areaname,jdbcType=VARCHAR}");
        }
        
        if (record.getLevel() != null) {
            sql.SET("level = #{level,jdbcType=TINYINT}");
        }
        
        if (record.getCitycode() != null) {
            sql.SET("cityCode = #{citycode,jdbcType=VARCHAR}");
        }
        
        if (record.getCenter() != null) {
            sql.SET("center = #{center,jdbcType=VARCHAR}");
        }
        
        if (record.getParentid() != null) {
            sql.SET("parentId = #{parentid,jdbcType=INTEGER}");
        }
        
        sql.WHERE("areaId = #{areaid,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_sms_address
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, IcSmsAddressExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}