package com.iconfluence.sms.mapper;

import com.iconfluence.sms.model.TestGenerator;
import com.iconfluence.sms.model.TestGeneratorExample;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TestGeneratorMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @SelectProvider(type=TestGeneratorSqlProvider.class, method="countByExample")
    long countByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TestGeneratorSqlProvider.class, method="deleteByExample")
    int deleteByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @Delete({
        "delete from test_generator",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @Insert({
        "insert into test_generator (id, code)",
        "values (#{id,jdbcType=INTEGER}, #{code,jdbcType=VARCHAR})"
    })
    int insert(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @InsertProvider(type=TestGeneratorSqlProvider.class, method="insertSelective")
    int insertSelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @SelectProvider(type=TestGeneratorSqlProvider.class, method="selectByExample")
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TestGenerator> selectByExample(TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, code",
        "from test_generator",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ConstructorArgs({
        @Arg(column="id", javaType=Integer.class, jdbcType=JdbcType.INTEGER, id=true),
        @Arg(column="code", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TestGenerator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TestGeneratorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TestGeneratorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TestGenerator record, @Param("example") TestGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TestGeneratorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TestGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_generator
     *
     * @mbg.generated
     */
    @Update({
        "update test_generator",
        "set code = #{code,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TestGenerator record);
}