ALTER TABLE `sms`.`ic_sms_contract` 
ADD COLUMN `PROJ_CODE` VARCHAR(32) NULL DEFAULT NULL AFTER `UID`,
ADD COLUMN `EN_NAME` VARCHAR(45) NULL DEFAULT NULL AFTER `PROJ_CODE`;


ALTER TABLE `sms`.`ic_sms_purchase` 
ADD COLUMN `REMARK` VARCHAR(640) NULL DEFAULT NULL AFTER `REG_TIME`;
